#!/usr/bin/env bash
# (c) 2020 Frabit Project maintained and limited by Blylei < blylei.info@gmail.com >
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
#
# This file is part of Frabit
#
set -x
SERVER="$1"

identify_os(){
  local os_version=$(cat /etc/os-release | grep ^NAME | awk -F"=" '{print $2}')
  echo "$os_version"
}

main(){
  pass

}

main